version: '3.5'
services:
  payments:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8081
    entrypoint: sh -c "payments server"
    environment:
      PORT: 8081
